package org.dsystems.rules.parser;

public enum TokenType {
	VARIABLE, 
	CONSTANT_DECIMAL,
	CONSTANT_STRING,
	KEYWORD,
	BINARYOPERATOR,
	UNARYOPERATOR,
	BRACKETS,
	ARITHMETICOPERATOR,
	COMPARISIONOPERATOR,
	FUNCTION, LOGICALOPERATOR;
}
